# Generated by Django 3.1.5 on 2021-06-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
